//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokTakipDbEntities : DbContext
    {
        public StokTakipDbEntities()
            : base("name=StokTakipDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barkod> Barkod { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunListe> UrunListe { get; set; }
        public virtual DbSet<UrunTakip> UrunTakip { get; set; }
    }
}
