//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int Id { get; set; }
        public Nullable<double> StokSayisi { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string StokTuru { get; set; }
    }
}
